name: upload_file
on: [push]
jobs:
  upload-file1:
    runs-on: ubuntu-latest
    steps:
      # 下载文件
      - name: Download File
        run: wget https://github.com/pitycycy/example-github-actions-helloworld/raw/refs/heads/main/hello.txt
      # 这将从您的工作流中上传工件，且允许您在工作流完成后在作业之间共享数据并存储数据
      - uses: actions/upload-artifact@v4
        with:
          name: my-artifact               # 文件名称
          path: hello.txt                 # 文件路径
          if-no-files-found: error        # 未找到文件时执行的操作
